site_name: Radbr Wiki
theme:
  name: material
  language: pt-BR
  palette:
    scheme: slate
docs_dir: docs
site_dir: site
nav:
  - Início: index.md
  - Outfits: outfits/index.md
  - Quests: quests/index.md
  - Itens: items/index.md
