site_name: Radbr Wiki
theme:
  name: material
  palette:
    scheme: slate
docs_dir: docs
site_dir: site
nav:
  - Home: index.md
  - Outfits: outfits/index.md
  - Quests: quests/index.md
  - Items: items/index.md
